[
    {
        "content": "<p>Hiya, on Ubuntu 21.10 I just checked out <code>rust-lang/rust:master</code>, ran <code>git clean -fdx</code>, <code>python3 ./x.py setup</code> (option <code>b</code>), then <code>python3 ./x.py test</code>, and it failed. Is that expected?</p>\n<div class=\"codehilite\"><pre><span></span><code>Documenting error index (x86_64-unknown-linux-gnu)\nBuilding stage0 tool error_index_generator (x86_64-unknown-linux-gnu)\n   Compiling same-file v1.0.6\n   Compiling walkdir v2.3.1\n   Compiling error_index_generator v0.0.0 (/home/bgeron/src/ext/rust/src/tools/error_index_generator)\n    Finished release [optimized] target(s) in 3.99s\n/home/bgeron/src/ext/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator: error while loading shared libraries: libLLVM-13-rust-1.59.0-nightly.so: cannot open shared object file: No such file or directory\n\n\ncommand did not execute successfully: &quot;/home/bgeron/src/ext/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator&quot; &quot;html&quot; &quot;/home/bgeron/src/ext/rust/build/x86_64-unknown-linux-gnu/doc/error-index.html&quot; &quot;1.59.0&quot;\nexpected success, got: exit status: 127\n\n\nBuild completed unsuccessfully in 0:47:10\n</code></pre></div>\n<p>This is on commit <code>16d8a91d5</code>. I'll try again on branch <code>stable</code>.</p>",
        "id": 265296303,
        "sender_full_name": "Bram Geron",
        "timestamp": 1639748410
    },
    {
        "content": "<p>Yeah, I think this is a known bug. Generally running <em>all</em> tests isn't something most people need to do locally, in this case you can likely fix by passing --stage 2 or so.</p>",
        "id": 265296484,
        "sender_full_name": "simulacrum",
        "timestamp": 1639748529
    },
    {
        "content": "<p><span aria-label=\"thumbs up\" class=\"emoji emoji-1f44d\" role=\"img\" title=\"thumbs up\">:thumbs_up:</span>  Thanks!</p>",
        "id": 265296507,
        "sender_full_name": "Bram Geron",
        "timestamp": 1639748544
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"465167\">Bram Geron</span> has marked this topic as resolved.</p>",
        "id": 265296690,
        "sender_full_name": "Notification Bot",
        "timestamp": 1639748680
    },
    {
        "content": "<p>I'm on Ubuntu 21.10 and don't have that failure</p>",
        "id": 265502402,
        "sender_full_name": "nnethercote",
        "timestamp": 1639951231
    }
]