[
    {
        "content": "<p>I'm not sure if this was already discussed and others are having a similar problem but I'm constantly getting ...</p>",
        "id": 169029578,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561555971
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span>failures:\n    [ui] ui/proc-macro/invalid-punct-ident-1.rs\n    [ui] ui/proc-macro/invalid-punct-ident-2.rs\n    [ui] ui/proc-macro/invalid-punct-ident-3.rs\n\ntest result: FAILED. 5685 passed; 3 failed; 21 ignored; 0 measured; 0 filtered out\n</pre></div>",
        "id": 169029587,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561555975
    },
    {
        "content": "<p>on my local machine, then I push my code and the those tests pass on the CI</p>",
        "id": 169029635,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561555997
    },
    {
        "content": "<p>this <a href=\"https://gist.github.com/spastorino/58b622690a37b24e394f3948c05b4d84\" target=\"_blank\" title=\"https://gist.github.com/spastorino/58b622690a37b24e394f3948c05b4d84\">https://gist.github.com/spastorino/58b622690a37b24e394f3948c05b4d84</a> is the full output</p>",
        "id": 169029824,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561556102
    },
    {
        "content": "<p>this just happens on stage 1, right?</p>",
        "id": 169044602,
        "sender_full_name": "oli",
        "timestamp": 1561564968
    },
    {
        "content": "<p>it happens on stage 1, unsure what would happen on stage 2</p>",
        "id": 169044661,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561565006
    },
    {
        "content": "<p>yea, these tests probably need a stage 1 skip comment, I don't remember the wording though</p>",
        "id": 169044805,
        "sender_full_name": "oli",
        "timestamp": 1561565081
    },
    {
        "content": "<p>look in <code>ui-fulldeps</code>, I think there are some comments in some files about stages</p>",
        "id": 169044821,
        "sender_full_name": "oli",
        "timestamp": 1561565095
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"124288\">@oli</span> <code>// ignore-stage1</code></p>",
        "id": 169047859,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561567151
    },
    {
        "content": "<p>but I wonder, does that happen to the rest of the people?</p>",
        "id": 169047879,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561567175
    },
    {
        "content": "<p>I thought it was just me</p>",
        "id": 169047884,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561567180
    },
    {
        "content": "<p>idk</p>",
        "id": 169048044,
        "sender_full_name": "oli",
        "timestamp": 1561567280
    },
    {
        "content": "<p>I get it as well when building stage1</p>",
        "id": 169051797,
        "sender_full_name": "Wesley Wiser",
        "timestamp": 1561570100
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"124288\">@oli</span> <a href=\"https://github.com/rust-lang/rust/pull/62157\" target=\"_blank\" title=\"https://github.com/rust-lang/rust/pull/62157\">https://github.com/rust-lang/rust/pull/62157</a></p>",
        "id": 169064144,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561572578
    },
    {
        "content": "<p>for the record these 3 tests fail when RUST_BACKTRACE is enabled</p>",
        "id": 169100680,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561605518
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"123856\">@Vadim Petrochenkov</span> about this, is expected that these tests fail when we turn on backtraces or not?, to be honest I'm on mobile right now and didn't put a lot of attention to them</p>",
        "id": 169140209,
        "sender_full_name": "Santiago Pastorino",
        "timestamp": 1561645960
    },
    {
        "content": "<p><a href=\"https://github.com/rust-lang/rust/issues/59998\" target=\"_blank\" title=\"https://github.com/rust-lang/rust/issues/59998\">https://github.com/rust-lang/rust/issues/59998</a> may be related?</p>",
        "id": 169140582,
        "sender_full_name": "Vadim Petrochenkov",
        "timestamp": 1561646267
    },
    {
        "content": "<p>It's expected than panicking in a proc macro will be caught and produce a regular error in rustc (without any backtraces), but this doesn't always happen apparently.</p>",
        "id": 169140717,
        "sender_full_name": "Vadim Petrochenkov",
        "timestamp": 1561646348
    }
]