[
    {
        "content": "<p>In <a href=\"https://github.com/rust-lang/rust/issues/81789\">#81789</a> CI reports a failure but I don't know how to repro locally. If I run the same command my build fails with dozens of different errors. Any tips?</p>",
        "id": 227892976,
        "sender_full_name": "osa1",
        "timestamp": 1614325674
    },
    {
        "content": "<p>It looks like you figured it out,  ci is passing now :)</p>",
        "id": 227935697,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1614349938
    },
    {
        "content": "<p>Yeah I fixed the problem, but not by running the failing test locally.. I just noticed in the error message that I have a typo..</p>",
        "id": 227965154,
        "sender_full_name": "osa1",
        "timestamp": 1614362014
    },
    {
        "content": "<p>Were the errors in <code>rustc_hir</code> and related to const-generics? I had that happen running <code>./x.py doc</code> and couldn't figure how to fix it: <a href=\"#narrow/stream/182449-t-compiler.2Fhelp/topic/x.2Epy.20doc.20errors\">https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/x.2Epy.20doc.20errors</a></p>",
        "id": 227982671,
        "sender_full_name": "Noah Lev",
        "timestamp": 1614369104
    }
]