[
    {
        "content": "<p>lately when I switch branches and build docs I often get an error like this one:</p>\n<div class=\"codehilite\"><pre><span></span><code>$ RUST_BACKTRACE=1 ./x.py doc library/std                                                                                                                                                     Updating only changed submodules\nUpdating submodule src/tools/miri\nSubmodule path &#39;src/tools/miri&#39;: checked out &#39;deb9bfd24648d50142ab29b810175837c4718885&#39;\n  Submodules updated in 0.08 seconds\nextracting /home/jsha/rust/rust/build/cache/e4b1d5841494d6eb7f4944c91a057e16b0f0a9ea/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz\nextracting /home/jsha/rust/rust/build/cache/e4b1d5841494d6eb7f4944c91a057e16b0f0a9ea/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz\nextracting /home/jsha/rust/rust/build/cache/e4b1d5841494d6eb7f4944c91a057e16b0f0a9ea/rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz\nBuilding rustbuild\n    Finished dev [unoptimized] target(s) in 0.09s\nDocumenting stage2 std (x86_64-unknown-linux-gnu)\nBuilding rustdoc for stage2 (x86_64-unknown-linux-gnu)\n   Compiling rustdoc v0.0.0 (/home/jsha/rust/rust/src/librustdoc)\nerror[E0514]: found crate `tracing` compiled by an incompatible version of rustc\n  --&gt; src/librustdoc/lib.rs:23:1\n   |\n23 | extern crate tracing;\n   | ^^^^^^^^^^^^^^^^^^^^^\n   |\n   = help: please recompile that crate using this compiler (rustc 1.60.0-nightly (e4b1d5841 2022-01-11)) (consider running `cargo clean` first)\n   = note: the following crate versions were found:\n           crate `tracing` compiled by rustc 1.60.0-nightly (f7bb8e367 2022-01-09): /home/jsha/rust/rust/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libtracing-dc3dfe641f9dba3a.rmeta\n\nerror[E0514]: found crate `itertools` compiled by an incompatible version of rustc\n --&gt; src/librustdoc/html/render/write_shared.rs:9:5\n  |\n9 | use itertools::Itertools;\n...\n</code></pre></div>\n<p>(many, many more errors follow)</p>\n<p><code>x.py clean</code> fixes it. I have the <code>tools</code> config profile set up.</p>\n<p>Any idea what's up? Have others run into this?</p>",
        "id": 267780239,
        "sender_full_name": "jsha",
        "timestamp": 1642018693
    },
    {
        "content": "<p>Yeah I get that sometimes. FYI, a tip that I learned from Joshua is to use <code>rm -r build/&lt;your-arch&gt;/stage*</code>; it avoids redownloading stuff, rebuilding internal tooling, etc.</p>",
        "id": 267780615,
        "sender_full_name": "Noah Lev",
        "timestamp": 1642018908
    }
]