[
    {
        "content": "<p>I found this strange behaviour where a local variable is not dropped when a destructor in the same scope panics: <a href=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=5e68a9ecbb2f4d61fff4faef592c2f07\" title=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=5e68a9ecbb2f4d61fff4faef592c2f07\">https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=5e68a9ecbb2f4d61fff4faef592c2f07</a></p>",
        "id": 196105981,
        "sender_full_name": "Diggsey",
        "timestamp": 1588516491
    },
    {
        "content": "<p>it seems to only happen if the local will be returned from the function</p>",
        "id": 196106048,
        "sender_full_name": "Diggsey",
        "timestamp": 1588516587
    },
    {
        "content": "<p>ah there's already an issue <a href=\"https://github.com/rust-lang/rust/issues/47949\" title=\"https://github.com/rust-lang/rust/issues/47949\">https://github.com/rust-lang/rust/issues/47949</a></p>",
        "id": 196106256,
        "sender_full_name": "Diggsey",
        "timestamp": 1588516963
    }
]